### ISSUE TITLE
Port or apply ODCA styles and branding

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#18]
We want our jekyll site to look like the [ODCA mocks](https://drive.google.com/drive/folders/18gBQCNYWM8m123EvbffQVZC7nvVxiPT_) and not necessarily the existing site. We should re-use the existing styles where possible but build towards the mocks if there is some divergence.

- [x] Copy minima files to repo, remove the minima gem theme
- [x] Scaffold base [SMACSS framework](https://smacss.com/)
- [x] Convert all the LESS to SASS so folks can take a look at the source and pull in what they want (but not commit it to `master`)
- [x] Port over base styles
- [x] Port components by page
  - [x] Header/footer #26 
  - [x] [Home](https://caciviclab.github.io/odca-jekyll/) #27 
  - [x] [Ballot](https://caciviclab.github.io/odca-jekyll/oakland/) #28 
  - [x] [Candidate](https://caciviclab.github.io/odca-jekyll/candidate/dan-kalb/) #29 
  - [x] [Referendum](https://caciviclab.github.io/odca-jekyll/referendum/oakland/2016-11-08/hh/) #30 
  - [x] [Referendum supporting/opposing](https://caciviclab.github.io/odca-jekyll/referendum/oakland/2016-11-08/hh/supporting) #31 
  - [x] [Committee](https://caciviclab.github.io/odca-jekyll/committee/1381041/) #32 
  - [x] [About](https://caciviclab.github.io/odca-jekyll/about/) #33

**Comment by adborden** [comment]
After looking through the LESS files, I don't think we just want to convert it all. It's not organized well and there are a mix of CSS architecture styles so it's inconsistent. I'd rather not take on that tech debt and spend some time to weed it out. I'm working on the base styles now, if that ends up being difficult, we might just pull in all the converted files to speed up the work.

**Comment by adborden** [comment]
I published this [less-to-sass-conversion](https://github.com/adborden/odca-jekyll/tree/less-to-sass-conversion) branch so folks can look at the converted LESS files. Not for merging ;)

**Comment by adborden** [comment]
Closing this out :tada:
